name: Push image to Docker Hub

on:
  push:
    branches: [ "develop"]
    paths: ['package.json']

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: thetiptop22
          password: dckr_pat_vuUrqw5GutctZUw6QMKScCfmTmc

      - uses: actions/checkout@v1

      - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: thetiptop22/dsp-archiwebf22-hm-hm-at-app-develop:latest,thetiptop22/dsp-archiwebf22-hm-hm-at-app-develop:${{ steps.package-node-version.outputs.version }}
