# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Push ressource to github Packages

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - uses: FrontEndDev-org/publish-node-package-action@v1
        with:
          target: github
